name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: my-job2-step
        run: echo "Hello World from job-2!" 
